/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import matest.*;

/**
 *
 * @author gaspar
 */
public class frmEjercicios extends javax.swing.JFrame {
    Lenguaje vg = new Lenguaje();
    private Ejercicios ej;
    private int opcion;
    private boolean porTiempo;
    private int c = 0;

    public void setPorTiempo(boolean porTiempo) {
        this.porTiempo = porTiempo;
    }
        
    public void constructor(int idiomaSeleccionado, Ejercicios ej, int opcion) {
        vg.setIdiomaSeleccionado(idiomaSeleccionado);
        this.ej = ej;
        this.opcion = opcion;
        myInitComponents();
    }
    
    /**
     * Creates new form frmEjercicios
     */
    public frmEjercicios() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Image imgIconoApp = new ImageIcon("src/vistas/icon.png").getImage();
        setIconImage(imgIconoApp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreEjercicios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEjercicio = new javax.swing.JTextArea();
        txtRespuesta = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("$_nombre_ejercicios");

        lblNombreEjercicios.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblNombreEjercicios.setText("$_Nombre_ejercicios");

        txtEjercicio.setEditable(false);
        txtEjercicio.setColumns(20);
        txtEjercicio.setFont(new java.awt.Font("Roboto Mono", 0, 18)); // NOI18N
        txtEjercicio.setLineWrap(true);
        txtEjercicio.setRows(5);
        txtEjercicio.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtEjercicio);

        txtRespuesta.setFont(new java.awt.Font("Roboto Mono", 0, 18)); // NOI18N
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        txtRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRespuestaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuestaKeyTyped(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblRespuesta.setText("$_Respuesta:");

        btnSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSiguiente.setText("$_siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblTiempo.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreEjercicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTiempo))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEjercicios)
                    .addComponent(lblTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here
        this.c ++;
        
        if (c == ej.getCantidadejercicios()) {
            ej.terminar();
        } else if (ej.getRespuesta() == Double.parseDouble(txtRespuesta.getText())) {
            if (this.porTiempo) {
                ej.setCantidadejercicios(ej.getCantidadejercicios() + 1);
            }
            
            ej.setRespuestasCorrectas(ej.getRespuestasCorrectas() + 1);
            txtRespuesta.setText("");
            txtRespuesta.requestFocus();
        }
        mostrarEjercicio();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuestaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaKeyTyped

    private void txtRespuestaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuestaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSiguiente.doClick();
        }
    }//GEN-LAST:event_txtRespuestaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicios().setVisible(true);
            }
        });
    }
    
    private void myInitComponents() {
        txtRespuesta.requestFocus();
        
        lblRespuesta.setText(vg.getRESPUESTA());
        btnSiguiente.setText(vg.getSIGUIENTE());
        
        switch(this.opcion) {
            case 1: // Suma
                lblNombreEjercicios.setText(vg.getSUMA());
                break;
            case 2: // Resta
                lblNombreEjercicios.setText(vg.getRESTA());
                break;
            case 3: // Multiplicacion
                lblNombreEjercicios.setText(vg.getMULTIPLICACION());
               break;
            case 4: // Division
                lblNombreEjercicios.setText(vg.getDIVISION());
                break;
            case 5: // Porcentaje
                lblNombreEjercicios.setText(vg.getPORCENTAGE());
                break;
        }
        
        this.setTitle(lblNombreEjercicios.getText());
    }
    
    public void iniciarCronometro() {
        JOptionPane.showMessageDialog(this, "Comenzar?");
        Thread nuevoHilo = Thread.currentThread();
        
        Runnable Cronometro = new Runnable() {
            @Override
            public void run() {
                int sec = 0;
                int min = 0;
                String tiempo;
                try {
                    while (true) {
                        nuevoHilo.sleep(1000);
                        sec ++;

                        if (sec == 60) {
                            sec = 0;
                            min ++;
                        }
                        
                        if (porTiempo) {
                            if (min == ej.getMinutos() && sec == ej.getSegundos()) {
                                ej.terminar();
                            }
                        } else {
                            ej.setMinutos(min);
                            ej.setSegundos(sec);
                        }
                        

                        if (min < 10) {
                            tiempo = "0" + min;
                        } else {
                            tiempo = min + "";
                        }

                        if (sec < 10) {
                            tiempo += ":0" + sec;
                        } else {
                            tiempo += ":" + sec;
                        }
                        
                        lblTiempo.setText(tiempo);
                    }
                } catch (InterruptedException e) {
                    System.err.println(e);
                    lblTiempo.setText("Error");
                }
            }
        };
                
        Thread cronThread = new Thread(Cronometro);
        
        cronThread.start();
        
        mostrarEjercicio();
    }
    
    public void mostrarEjercicio() {
        switch(this.opcion) {
            case 1: // Suma
                txtEjercicio.setText(ej.generarSuma());
                break;
            case 2: // Resta
                txtEjercicio.setText(ej.generarResta());
                break;
            case 3: // Multiplicacion
                txtEjercicio.setText(ej.generarMultiplicacion()); 
                break;
            case 4: // Division
                txtEjercicio.setText(ej.generarDivision());
                break;
            case 5: // Porcentaje
                txtEjercicio.setText(ej.generarPorcentage());
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreEjercicios;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JTextArea txtEjercicio;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
