/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import javax.swing.ImageIcon;
import matest.*;

/**
 *
 * @author gaspar
 */
public class frmFormulario extends javax.swing.JFrame {
    Lenguaje vg = new Lenguaje();
    private Ejercicios ej;
    private int opcion; 
    
    public void constructor(int idiomaSeleccionado, Ejercicios ej, int opcion) {
        vg.setIdiomaSeleccionado(idiomaSeleccionado);
        this.ej = ej;
        this.opcion = opcion;
        myInitComponents();
    }
            
    /**
     * Creates new form frmFormulario
     */
    public frmFormulario() {
        initComponents();
        porTiempo(true);
        this.setLocationRelativeTo(null);
        
        Image imgIconoApp = new ImageIcon("src/vistas/icon.png").getImage();
        setIconImage(imgIconoApp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lblNombreEjercicios = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        lblTiempo = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        lblMinutos = new javax.swing.JLabel();
        txtSegundos = new javax.swing.JTextField();
        lblSegundos = new javax.swing.JLabel();
        lblCantidadEjercicios = new javax.swing.JLabel();
        txtCantidadEjercicios = new javax.swing.JTextField();
        spnDigitos = new javax.swing.JSpinner();
        lblDigitos = new javax.swing.JLabel();
        lblCifras = new javax.swing.JLabel();
        spnCifras = new javax.swing.JSpinner();
        rdbTiempo = new javax.swing.JRadioButton();
        rdbEjercicios = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombreEjercicios.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblNombreEjercicios.setText("$_Nombre_ejercicios");

        btnSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSiguiente.setText("$_Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblTiempo.setText("Tiempo");

        txtMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosActionPerformed(evt);
            }
        });

        lblMinutos.setText("Min");

        lblSegundos.setText("Sec");

        lblCantidadEjercicios.setText("Cantidad de ejercicios");

        txtCantidadEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEjerciciosActionPerformed(evt);
            }
        });

        lblDigitos.setText("Digitos");

        lblCifras.setText("Cifras");

        rdbTiempo.setText("Por tiempo");
        rdbTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTiempoActionPerformed(evt);
            }
        });

        rdbEjercicios.setText("Por ejercicios");
        rdbEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEjerciciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidadEjercicios)
                            .addComponent(lblDigitos)
                            .addComponent(lblCifras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCifras)
                            .addComponent(spnDigitos)
                            .addComponent(txtCantidadEjercicios)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreEjercicios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTiempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinutos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMinutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSegundos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSegundos))
                            .addComponent(rdbEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreEjercicios)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbTiempo)
                    .addComponent(rdbEjercicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempo)
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinutos)
                    .addComponent(txtSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadEjercicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnDigitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigitos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCifras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCifras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEjerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEjerciciosActionPerformed

    private void txtMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosActionPerformed

    private void rdbTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTiempoActionPerformed
        // TODO add your handling code here:
        porTiempo(true);
    }//GEN-LAST:event_rdbTiempoActionPerformed

    private void rdbEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEjerciciosActionPerformed
        // TODO add your handling code here:
        porTiempo(false);
    }//GEN-LAST:event_rdbEjerciciosActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        ej.setMinutos(Integer.parseInt(txtMinutos.getText()));
        ej.setSegundos(Integer.parseInt(txtSegundos.getText()));
        ej.setCantidadejercicios(Integer.parseInt(txtCantidadEjercicios.getText()));
        ej.setDigitos((int)spnDigitos.getValue());
        ej.setCifras((int)spnCifras.getValue());
        ej.mostrarEjercicios();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFormulario().setVisible(true);
            }
        });
    }
    
    private void myInitComponents() {
        rdbTiempo.setText(vg.getPOR_TIEMPO());
        rdbEjercicios.setText(vg.getPOR_EJERCICIOS());
        lblTiempo.setText(vg.getTIEMPO());
        lblMinutos.setText(vg.getMINUTOS());
        lblSegundos.setText(vg.getSEGUNDOS());
        lblCantidadEjercicios.setText(vg.getCANTIDAD_EJERCICIOS());
        lblDigitos.setText(vg.getDIGITOS());
        lblCifras.setText(vg.getCIFRAS());
        btnSiguiente.setText(vg.getCOMENZAR());
        
        switch(this.opcion) {
            case 1: // Suma
                lblNombreEjercicios.setText(vg.getSUMA());
                break;
            case 2: // Resta
                lblNombreEjercicios.setText(vg.getRESTA());
                break;
            case 3: // Multiplicacion
                lblNombreEjercicios.setText(vg.getMULTIPLICACION());
               break;
            case 4: // Division
                lblNombreEjercicios.setText(vg.getDIVISION());
                break;
            case 5: // Porcentaje
                lblNombreEjercicios.setText(vg.getPORCENTAGE());
                break;
        }
        this.setTitle(lblNombreEjercicios.getText());
    }
    
    private void porTiempo(boolean porTiempo) {
        lblCantidadEjercicios.setVisible(!porTiempo);
        txtCantidadEjercicios.setVisible(!porTiempo);
        
        lblTiempo.setVisible(porTiempo);
        txtMinutos.setVisible(porTiempo);
        lblMinutos.setVisible(porTiempo);
        txtSegundos.setVisible(porTiempo);
        lblSegundos.setVisible(porTiempo);
        
        rdbTiempo.setSelected(porTiempo);
        rdbEjercicios.setSelected(!porTiempo);
        
        
        txtCantidadEjercicios.setText("0");
        txtMinutos.setText("0");
        txtSegundos.setText("0");
    }
    
    public void ocultarCifras() {
        lblCifras.setVisible(false);
        spnCifras.setVisible(false);
        spnCifras.setValue(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel lblCantidadEjercicios;
    private javax.swing.JLabel lblCifras;
    private javax.swing.JLabel lblDigitos;
    private javax.swing.JLabel lblMinutos;
    private javax.swing.JLabel lblNombreEjercicios;
    private javax.swing.JLabel lblSegundos;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JRadioButton rdbEjercicios;
    private javax.swing.JRadioButton rdbTiempo;
    private javax.swing.JSpinner spnCifras;
    private javax.swing.JSpinner spnDigitos;
    private javax.swing.JTextField txtCantidadEjercicios;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtSegundos;
    // End of variables declaration//GEN-END:variables
}
