/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import javax.swing.ImageIcon;
import matest.*;

/**
 *
 * @author gaspar
 */
public class frmResumen extends javax.swing.JFrame {
    Lenguaje vg = new Lenguaje();
    private Ejercicios ej;
        
    public void constructor(int idiomaSeleccionado, Ejercicios ej) {
        vg.setIdiomaSeleccionado(idiomaSeleccionado);
        this.ej = ej;
        myInitComponents();
    }
    
    /**
     * Creates new form frmResumen
     */
    public frmResumen() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Image imgIconoApp = new ImageIcon("src/vistas/icon.png").getImage();
        setIconImage(imgIconoApp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResumen = new javax.swing.JLabel();
        lblCantidadEjercicios = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblTiempoPromedio = new javax.swing.JLabel();
        lblMostrarCantidadEjercicios = new javax.swing.JLabel();
        lblMostrarTiempo = new javax.swing.JLabel();
        lblMostrarTiempoPromedio = new javax.swing.JLabel();
        lblRespuestasCorrectas = new javax.swing.JLabel();
        lblMostrarRespuestasCorrectas = new javax.swing.JLabel();
        lblMostrarPuntaje = new javax.swing.JLabel();
        btnReintentar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblPuntaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        lblResumen.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblResumen.setText("$_resumen");

        lblCantidadEjercicios.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCantidadEjercicios.setText("$_cantidad_ejercicios");

        lblTiempo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTiempo.setText("$_tiempo");

        lblTiempoPromedio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTiempoPromedio.setText("$_tiempo_promedio");

        lblMostrarCantidadEjercicios.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMostrarCantidadEjercicios.setText("jLabel1");

        lblMostrarTiempo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMostrarTiempo.setText("jLabel2");

        lblMostrarTiempoPromedio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMostrarTiempoPromedio.setText("jLabel3");

        lblRespuestasCorrectas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblRespuestasCorrectas.setText("$_respuestas_correctas");

        lblMostrarRespuestasCorrectas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMostrarRespuestasCorrectas.setText("1");

        lblMostrarPuntaje.setFont(new java.awt.Font("Roboto", 1, 72)); // NOI18N
        lblMostrarPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarPuntaje.setText("c/t");

        btnReintentar.setText("$_reintentar");
        btnReintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReintentarActionPerformed(evt);
            }
        });

        btnGuardar.setText("$_guardar");

        btnCerrar.setText("$_cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblPuntaje.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPuntaje.setText("$_puntaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMostrarPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantidadEjercicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMostrarCantidadEjercicios))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTiempoPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMostrarTiempoPromedio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTiempo)
                            .addComponent(lblRespuestasCorrectas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMostrarTiempo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMostrarRespuestasCorrectas, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReintentar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResumen)
                            .addComponent(lblPuntaje))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadEjercicios)
                    .addComponent(lblMostrarCantidadEjercicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespuestasCorrectas)
                    .addComponent(lblMostrarRespuestasCorrectas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempo)
                    .addComponent(lblMostrarTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoPromedio)
                    .addComponent(lblMostrarTiempoPromedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuntaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostrarPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReintentar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnReintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReintentarActionPerformed
        // TODO add your handling code here:
        // ej.repetirEjercicios(vg.getIdiomaSeleccionado());
    }//GEN-LAST:event_btnReintentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmResumen().setVisible(true);
            }
        });
    }

    private void myInitComponents() {
        this.setTitle(vg.getRESUMEN());
        
        lblResumen.setText(vg.getRESUMEN());
        lblCantidadEjercicios.setText(vg.getCANTIDAD_EJERCICIOS());
        lblRespuestasCorrectas.setText(vg.getRESPUESTAS_CORRECTAS());
        lblTiempo.setText(vg.getTIEMPO());
        lblTiempoPromedio.setText(vg.getTIEMPO_PROMEDIO());
        lblPuntaje.setText(vg.getPUNTAJE());
        
        btnGuardar.setText(vg.getGUARDAR());
        btnReintentar.setText(vg.getREINTENTAR());
        btnCerrar.setText(vg.getCERRAR());
    }
    
    public void llenar() {
        String tiempo = "";
        
        int min = ej.getMinutos();
        int sec = ej.getSegundos();
        
        int cantidadejercicios = ej.getCantidadejercicios();
        int respuestasCorrectas = ej.getRespuestasCorrectas();
        
        if (min < 10) {
            tiempo = "0" + min;
        } else {
            tiempo = min + "";
        }

        if (sec < 10) {
            tiempo += ":0" + sec;
        } else {
            tiempo += ":" + sec;
        }
        
        sec = min * 60 + sec;
        
        
        float tiempoPromedio = (float) sec / cantidadejercicios;
        float puntaje = (float) respuestasCorrectas / sec;
        
        lblMostrarCantidadEjercicios.setText(cantidadejercicios + "");
        lblMostrarRespuestasCorrectas.setText(respuestasCorrectas + "");
        lblMostrarTiempo.setText(tiempo);
        lblMostrarTiempoPromedio.setText(tiempoPromedio + " s");
        lblMostrarPuntaje.setText(puntaje + "");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReintentar;
    private javax.swing.JLabel lblCantidadEjercicios;
    private javax.swing.JLabel lblMostrarCantidadEjercicios;
    private javax.swing.JLabel lblMostrarPuntaje;
    private javax.swing.JLabel lblMostrarRespuestasCorrectas;
    private javax.swing.JLabel lblMostrarTiempo;
    private javax.swing.JLabel lblMostrarTiempoPromedio;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblRespuestasCorrectas;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempoPromedio;
    // End of variables declaration//GEN-END:variables
}
